# Generated by Django 5.2.4 on 2025-08-27 08:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('department', models.CharField(choices=[('bca', 'BCA'), ('computerscience', 'CSE'), ('mechanical', 'ME'), ('civil', 'CV')], max_length=30)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
